/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIME_H_RPCGEN
#define _TIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define Time 0x20000001
#define Time_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define getTime 1
extern  char ** gettime_1(void *, CLIENT *);
extern  char ** gettime_1_svc(void *, struct svc_req *);
extern int time_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getTime 1
extern  char ** gettime_1();
extern  char ** gettime_1_svc();
extern int time_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIME_H_RPCGEN */
