/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "time.h"


void
time_1(char *host)
{
	CLIENT *clnt;
	char * *result;
	char *gettime_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, Time, Time_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result = gettime_1((void*)&gettime_1_arg, clnt);
	if (result == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("The current date and time is: %s", *result);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	time_1 (host);
exit (0);
}
