/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_1(char *host)
{
	CLIENT *clnt;
	float  *result;
	numbers  arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC, CALC, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Enter arithmetic equation : ");
	char ch;
	scanf("%f %c %f", &arg.a, &ch, &arg.b );
	printf("%f %c %f = ", arg.a, ch, arg.b );
	switch (ch)
	{
		case '+': {
			result = add_1(&arg, clnt);
			if (result == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("%f \n", *result);
			}
			break;
		}
		case '-':{
			result = sub_1(&arg, clnt);
			if (result == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("%f \n", *result);
			}
			break;
		}
		case '*':{
			result = mul_1(&arg, clnt);
			if (result == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("%f \n", *result);
			}
			break;
		}
		case '/':{
			result = div_1(&arg, clnt);
			if(arg.b == 0.0){
				printf("ERROR\n Division by zero is not possible\n");
			}
			else if (result == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("%f \n", *result);
			}
			break;
		}
		default:{
			printf("Invalid operator \n");
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_1 (host);
exit (0);
}
