/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CHAT_PROG 0x23454222
#define CHAT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_message 1
extern  char ** send_message_1(char **, CLIENT *);
extern  char ** send_message_1_svc(char **, struct svc_req *);
extern int chat_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_message 1
extern  char ** send_message_1();
extern  char ** send_message_1_svc();
extern int chat_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
